version: '3.8'

services:
  laravelback:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:dev
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app-network
  
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: attendanceDB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge